# Generated by Django 5.1 on 2024-08-23 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='id do instrutor', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='nome do instrutor', max_length=70)),
                ('rg', models.CharField(help_text='rg do instrutor', max_length=9)),
                ('datadenascimento', models.DateField(help_text='data de nascimento')),
                ('ddd', models.CharField(blank=True, help_text='ddd do intrutor', max_length=3)),
                ('telefone', models.CharField(blank=True, help_text='telefone do intrutor', max_length=9)),
                ('titularidade', models.CharField(help_text='titularidade do instrutor', max_length=70)),
            ],
        ),
    ]
