# Generated by Django 5.0.8 on 2024-08-23 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aluno', '0002_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='matricula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='nome do aluno', max_length=70)),
                ('datainicial', models.DateField(help_text='data inicial')),
                ('datafinal', models.DateField(blank=True, help_text='data final', null=True)),
            ],
        ),
    ]
