# Generated by Django 5.1 on 2024-08-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Numero', primary_key=True, serialize=False)),
                ('horariodaaula', models.TimeField(help_text='horario da aula')),
                ('duracaodaaula', models.TimeField(help_text='duracao da aula')),
                ('datainicial', models.DateField(help_text='data inicial')),
                ('datafinal', models.DateField(blank=True, help_text='data final', null=True)),
                ('instrutor', models.CharField(help_text='nome do instrutor', max_length=70)),
                ('alunomonitor', models.CharField(help_text='aluno monitor', max_length=70)),
                ('titularidade', models.CharField(help_text='titularidade do instrutor', max_length=70)),
            ],
        ),
    ]
