# Generated by Django 5.1 on 2024-08-23 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0002_turma_atividade_alter_turma_duracaodaaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracaodaaula',
            field=models.TimeField(help_text='duracao da aula'),
        ),
    ]
