# Generated by Django 5.1 on 2024-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turma', '0003_alter_turma_duracaodaaula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='duracaodaaula',
            field=models.CharField(help_text='duracao da aula', max_length=2),
        ),
    ]
